# Generated by Django 4.0.4 on 2022-04-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_academictours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academictours',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
