# Generated by Django 4.0.4 on 2022-04-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_pastevents_upcomingevents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upcomingevents',
            old_name='date',
            new_name='event_date',
        ),
    ]
