# Generated by Django 4.0.4 on 2022-04-27 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_pastevents_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upcoming_events')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.upcomingevents')),
            ],
        ),
        migrations.CreateModel(
            name='PastEventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='past_events')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.pastevents')),
            ],
        ),
    ]
