# Generated by Django 4.0.4 on 2022-04-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_upcomingeventgallery_pasteventgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevents',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
