# Generated by Django 4.0.4 on 2022-04-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_homepagegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinquiry',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courseinquiry',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
    ]
