# Generated by Django 4.0.4 on 2022-04-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_courseinquiry_ip_address_courseinquiry_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseInquiry',
            new_name='Enquiries',
        ),
    ]
