# Generated by Django 4.0.4 on 2022-04-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_enquirystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirystatus',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
