# Generated by Django 4.0.4 on 2022-04-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_enquiries_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiries',
            name='address',
        ),
        migrations.AddField(
            model_name='enquiries',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
