# Generated by Django 4.0.4 on 2022-04-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_appsetting_top_header_popup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppSetting',
            new_name='WebsiteSettings',
        ),
    ]
