# Generated by Django 4.0.4 on 2022-04-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='top_header_popup_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
