# Generated by Django 4.0.4 on 2022-04-30 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_mediacoverage_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_upcoming',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='past_events')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.events')),
            ],
        ),
    ]
