# Generated by Django 4.0.4 on 2022-04-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_remove_events_time_alter_events_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
