# Generated by Django 4.0.4 on 2022-05-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_academictours_show_at_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
