# Generated by Django 4.0.4 on 2022-11-13 17:52

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0053_jurymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='academictours',
            name='course_type',
            field=models.CharField(blank=True, choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='awards',
            name='course_type',
            field=models.CharField(blank=True, choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='course_type',
            field=models.CharField(blank=True, choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='globalopportunities',
            name='course_type',
            field=models.CharField(blank=True, choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='course_type',
            field=models.CharField(blank=True, choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='course_type',
            field=models.CharField(blank=True, choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mediacoverage',
            name='course_type',
            field=models.CharField(blank=True, choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentors',
            name='course_type',
            field=models.CharField(blank=True, choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partners',
            name='course_type',
            field=models.CharField(blank=True, choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='placementpartners',
            name='course_type',
            field=models.CharField(blank=True, choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='placements',
            name='course_type',
            field=models.CharField(blank=True, choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentwork',
            name='course_type',
            field=models.CharField(blank=True, choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='course_type',
            field=models.CharField(blank=True, choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='course_type',
            field=models.CharField(blank=True, choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('course_type', models.CharField(blank=True, choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
