# Generated by Django 4.0.4 on 2022-12-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_enquiryformotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiries',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
