# Generated by Django 4.0.4 on 2023-02-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_inhousementor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('course_type', models.CharField(blank=True, choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='collaboration')),
                ('show_at_home', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
