# Generated by Django 4.0.4 on 2023-02-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_collaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhousementor',
            name='show_at_home',
            field=models.BooleanField(default=True),
        ),
    ]
