# Generated by Django 4.0.4 on 2023-03-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_collaboration_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_1_year', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_1_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_1_board', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_1_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_2_year', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_2_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_2_board', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_2_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_3_year', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_3_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_3_board', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_3_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(blank=True, choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
