# Generated by Django 4.0.4 on 2023-03-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_course_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('interior', 'Interior Design'), ('fashion', 'Fashion Design')], max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_type', 'name')},
        ),
    ]
