# Generated by Django 4.0.4 on 2023-03-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0066_careeroptions_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admission'),
        ),
    ]
